<BodyContainer>:
    MDFloatLayout:
        id: container
        pos_hint: {'center_x': .5 , 'center_y': .5}

        #ServerDetails:
        #    target: root.target
        #    pos_hint: {'center_x': .15 , 'center_y': .525}

    MDSpinner:
        size_hint: None, None
        height: 200
        width: 200
        index: 10
        line_width: 5
        palette: root.spinner_palette
        pos_hint: {'center_x': .5, 'center_y': .5}
        active: root.spinner
